### ISSUE TITLE
svelte variables are undefined

### ISSUE THREAD

**Issue by Equisetum** [Rich-Harris/svelte-template-electron#2]
I have succesfully build and run the template. 
But now I'am trying to make it a litte bit more dynamic with a svelte variable, and it gives me an undefined in the output instead of the value. 

Down here is the code I wrote in App.html. Also when I change this in App.svelte  it doesn't help.
I tried splitting the h1 to an component but this doesn't work either.
Can you please give me a hint on what I'm doing wrong? Looks lik the svelte magic isn't working

<script>
	let message = 'Hello k...';
</script>

<style>
	h1 {
		font-family: 'Comic Sans MS';
		font-weight: 300;
		color: green;
		margin: 2em auto;
		text-align: center;
	}
</style>

<h1>{message} world!</h1>

**Comment by rickhall** [comment]
Just some more information. It appears that the variables are initially undefined. If I bind a variable to an input field and display the value in the template, the initial value is undefined, but if I edit the value then it is correctly updated in the template.

**Comment by rickhall** [comment]
Looking into it more closely, it just appears that this project template is majorly out of date. Anyone aware of an Electron project template that integrates Svelte 3?

**Comment by Equisetum** [comment]
I found this one: https://github.com/Blade67/Sveltron
And it works!

**Comment by rickhall** [comment]
Funny, you'd think an "electron svelte" google search would have found that one, but I guess it is pretty fresh, thanks!

**Comment by fractalf** [comment]
Tried this one, yea probably outdated. Tried the Balde67 template... meh
Found this one https://github.com/jzillmann/template-electron-svelte perfect! :)
